version:"3"

services:
  app:
    container_name: healthcare
    build: ./
    depends_on:
      - dbpostgresql
    dbpostgresql:
      image: postgres
      ports:
        - "5432:5432"
    environment:
      - SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/postgres
      - SPRING_DATASOURCE_USERNAME:postgres
      - SPRING_DATASOURCE_PASSWORD:sant123
      - SPRING_JPA_GENERATE-DDL:true
      - SERVER_PORT:8081\